### ISSUE TITLE
maxDataSize:0 crashes the app when using koa and ctx is captured

### ISSUE THREAD

**Issue by kilianc** [googleapis/cloud-debug-nodejs#450] opened 2018-06-22 02:21 UTC
I am not sure if this is due to memory maxing out or something else. I also don't have a proposal/solution.

I think something weird is happening with `ctx` circular references and the way data is serialized.

Setting `maxDataSize` to 1MB (1048576) works perfectly but blocks for about 3s

**Comment by DominicKramer** [comment] 2018-06-22 03:40
Thanks for opening this issue.  I agree this could potentially be caused by circular references in `ctx`, but I'll have to look into it in more detail.  I'll keep this thread updated with what I find.

**Comment by kjin** [comment] 2018-08-28 00:03
https://github.com/GoogleCloudPlatform/cloud-debug-nodejs/blob/a136e143530aa14bb36d0aaa93c830159b8bceae/src/agent/config.ts#L211-L219

`maxDataSize: 0` specifies no limit in the amount of data returned, so @kilianc's theory that getting an expression with a circular reference causes an issue seems to be correct. We can avoid this by either setting a hard upper limit even if the user asks for none, or detecting circular references. @DominicKramer thoughts?

**Comment by JustinBeckwith** [comment] 2018-09-11 18:04
@DominicKramer @ofrobots Assigning this to @DominicKramer since P1s should be assigned and active :)

**Comment by kjin** [comment] 2018-09-11 18:07
Pending a new release, this should be fixed for Node <10. The same bug for Node 10 is being tracked in #516.

**Comment by DominicKramer** [comment] 2018-09-19 16:53
I am closing this issue since it has been resolved for Node < 10 with the release of version 3.0.0.  Further conversation about the solution for Node 10 should occur on issue #516.  Any issues anyone finds with Node < 10 should be reported in this thread.

**Closed by DominicKramer** 2018-09-19 16:53 UTC
Labels: :rotating_light:, priority: p1, type: bug

**Comment by kjin** [comment] 2019-08-18 21:53
FYI, the feature needed to fix this bug was removed in Node 12, so this bug now appears once again in all versions of Node 12+. To work around it, use a non-zero `maxDataSize` value.

This bug will likely not be fixable unless Node adds this feature back.
