### ISSUE TITLE
Occasionally getting error in Stackdriver logs

### ISSUE THREAD

**Issue by ggprod** [googleapis/cloud-debug-nodejs#401] opened 2018-02-23 03:17 UTC
ERROR:@google-cloud/debug-agent: Error: Unable to clear breakpoint in v8

**Comment by DominicKramer** [comment] 2018-02-26 18:28
Thank you for reporting this.  Do you have a rough estimate of how often this is occurring?  Also, are you able to use the debug agent, and are just seeing these errors in the logs, or is functionality of the debug agent not working as expected in addition to seeing the errors in the logs?  Thanks.

**Comment by ggprod** [comment] 2018-02-26 20:41
It only seems to happen when setting watchpoints in the stackdriver debugger.. and only sporadically.

Yes, I'm able to use the debug agent with no functionality problems noticed

**Comment by DominicKramer** [comment] 2018-02-26 21:57
Ok thanks for letting me know.  That helps in investigating the cause, and I'll update this thread as I learn more.

**Comment by DominicKramer** [comment] 2018-09-28 00:15
I have not been able to reproduce this on Node 6, 8, or 10 using the new release of the debug agent 3.0.0.  I am going to close this for now, and will re-open it if the error message reappears.

**Closed by DominicKramer** 2018-09-28 00:15 UTC
Labels: :rotating_light:, priority: p2, type: bug

**Comment by nagaland88** [comment] 2018-10-30 17:02
@DominicKramer  we are getting the same error 

@google-cloud/debug-agent Error: Unable to clear breakpoint in v8
    at Object.setErrorStatusAndCallback (/usr/src/app/node_modules/@google-cloud/debug-agent/build/src/agent/util/utils.js:143:19)
    at V8DebugApi.clear (/usr/src/app/node_modules/@google-cloud/debug-agent/build/src/agent/v8/legacy-debugapi.js:115:26)
    at Debuglet.removeBreakpoint_ (/usr/src/app/node_modules/@google-cloud/debug-agent/build/src/agent/debuglet.js:651:26)
    at that.controller.updateBreakpoint (/usr/src/app/node_modules/@google-cloud/debug-agent/build/src/agent/debuglet.js:734:22)
    at request (/usr/src/app/node_modules/@google-cloud/debug-agent/build/src/agent/controller.js:135:17)
    at /usr/src/app/node_modules/@google-cloud/common/build/src/service-object.js:278:61
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)

node8 and debug agent 3.0.0
