### ISSUE TITLE
Unhandled rejection `properties.project` is not a string

### ISSUE THREAD

**Issue by ofrobots** [googleapis/cloud-debug-nodejs#661] opened 2019-03-29 17:26 UTC
With the latest version I get the following error on a simple test

```js
require('@google-cloud/debug-agent').start();

setTimeout(() => {}, 10000);

```

Output
```
❯ node index.js
(node:74342) UnhandledPromiseRejectionWarning: Error: properties.project must be a string
    at new Debuggee (/Users/ofrobots/tmp/debug-test/node_modules/@google-cloud/debug-agent/build/src/debuggee.js:50:19)
    at Function.createDebuggee (/Users/ofrobots/tmp/debug-test/node_modules/@google-cloud/debug-agent/build/src/agent/debuglet.js:412:16)
    at Debuglet.<anonymous> (/Users/ofrobots/tmp/debug-test/node_modules/@google-cloud/debug-agent/build/src/agent/debuglet.js:327:38)
    at Generator.throw (<anonymous>)
    at rejected (/Users/ofrobots/tmp/debug-test/node_modules/@google-cloud/debug-agent/build/src/agent/debuglet.js:20:65)
(node:74342) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:74342) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Note that I did `gcloud auth revoke` before running the above.

**Comment by DominicKramer** [comment] 2019-03-29 17:48
I have confirmed that the unhandled rejection doesn't occur unless `gcloud auth revoke` is run.

**Comment by DominicKramer** [comment] 2019-03-29 18:07
This is occurring because the debug agent is asking `@google-cloud/common` for the project ID that then asks `google-auth-library` for the project ID in the [getProjectIdAsync()](https://github.com/googleapis/google-auth-library-nodejs/blob/ec56c8897f64863a6f0f8ab760ed7c9ad6f6778f/src/auth/googleauth.ts#L176) method.

The problem is if the project ID could not be resolved, the promise is resolved in the `getProjectIdAsync()` method with a value of `null`.

The debug agent could be modified so that the agent emits an `initError` [here](https://github.com/googleapis/cloud-debug-nodejs/blob/5e4f79451923e6592393bdd2a11d5dd9498261ab/src/agent/debuglet.ts#L376), or the `getProjectIdAsync()` method in `google-auth-library` could be modified to reject the promise it returns if the project could not be determined.

I suggest modifying the `getProjectIdAsync()` method.  @JustinBeckwith do you see any problems with this approach?

**Comment by JustinBeckwith** [comment] 2019-03-29 18:33
Nope - that sounds right.  I can take this one :)

**Comment by ofrobots** [comment] 2019-03-29 18:39
@JustinBeckwith should I assign this to you, or are you planning to move this issue to `gal`?

**Comment by DominicKramer** [comment] 2019-04-01 17:02
I've unassigned myself because @JustinBeckwith is working on this.

**Comment by JustinBeckwith** [comment] 2019-08-24 23:07
So I just tried this with the latest everything, and get this error:

```js
@google-cloud/debug-agent The project ID could not be determined: Unable to detect a Project Id in the current environment. 
To learn more about authentication and Google APIs, visit: 
https://cloud.google.com/docs/authentication/getting-started
```

That looks a lot better than it used to :)  I don't remember fixing it, but I'm calling this one good!

**Closed by JustinBeckwith** 2019-08-24 23:07 UTC
Labels: priority: p2, status: blocked, type: bug
